/*
 * This file is generated by jOOQ.
 */
package org.example.businesspack.bd;


import java.util.Arrays;
import java.util.List;

import org.example.businesspack.bd.tables.DataWork;
import org.example.businesspack.bd.tables.Person;
import org.example.businesspack.bd.tables.TabStatus;
import org.example.businesspack.bd.tables.UserData;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>data_work</code>.
     */
    public final DataWork DATA_WORK = DataWork.DATA_WORK;

    /**
     * The table <code>person</code>.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * The table <code>tab_status</code>.
     */
    public final TabStatus TAB_STATUS = TabStatus.TAB_STATUS;

    /**
     * The table <code>user_data</code>.
     */
    public final UserData USER_DATA = UserData.USER_DATA;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DataWork.DATA_WORK,
            Person.PERSON,
            TabStatus.TAB_STATUS,
            UserData.USER_DATA
        );
    }
}
