/*
 * This file is generated by jOOQ.
 */
package org.example.businesspack.bd;


import org.example.businesspack.bd.tables.DataWork;
import org.example.businesspack.bd.tables.Person;
import org.example.businesspack.bd.tables.UserData;
import org.example.businesspack.bd.tables.records.DataWorkRecord;
import org.example.businesspack.bd.tables.records.PersonRecord;
import org.example.businesspack.bd.tables.records.UserDataRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DataWorkRecord> DATA_WORK__PK_DATA_WORK = Internal.createUniqueKey(DataWork.DATA_WORK, DSL.name("pk_data_work"), new TableField[] { DataWork.DATA_WORK.ID }, true);
    public static final UniqueKey<PersonRecord> PERSON__PK_PERSON = Internal.createUniqueKey(Person.PERSON, DSL.name("pk_person"), new TableField[] { Person.PERSON.ID }, true);
    public static final UniqueKey<UserDataRecord> USER_DATA__PK_USER_DATA = Internal.createUniqueKey(UserData.USER_DATA, DSL.name("pk_user_data"), new TableField[] { UserData.USER_DATA.ID }, true);
}
