/*
 * This file is generated by jOOQ.
 */
package org.example.businesspack.bd;


import org.example.businesspack.bd.tables.DataWork;
import org.example.businesspack.bd.tables.Person;
import org.example.businesspack.bd.tables.TabStatus;
import org.example.businesspack.bd.tables.UserData;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>data_work</code>.
     */
    public static final DataWork DATA_WORK = DataWork.DATA_WORK;

    /**
     * The table <code>person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>tab_status</code>.
     */
    public static final TabStatus TAB_STATUS = TabStatus.TAB_STATUS;

    /**
     * The table <code>user_data</code>.
     */
    public static final UserData USER_DATA = UserData.USER_DATA;
}
