/*
 * This file is generated by jOOQ.
 */
package org.example.businesspack.bd;


import org.example.businesspack.bd.tables.DataWork;
import org.example.businesspack.bd.tables.JournalWork;
import org.example.businesspack.bd.tables.Maintenance;
import org.example.businesspack.bd.tables.Person;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>data_work</code>.
     */
    public static final DataWork DATA_WORK = DataWork.DATA_WORK;

    /**
     * The table <code>journal_work</code>.
     */
    public static final JournalWork JOURNAL_WORK = JournalWork.JOURNAL_WORK;

    /**
     * The table <code>maintenance</code>.
     */
    public static final Maintenance MAINTENANCE = Maintenance.MAINTENANCE;

    /**
     * The table <code>person</code>.
     */
    public static final Person PERSON = Person.PERSON;
}
