/*
 * This file is generated by jOOQ.
 */
package org.example.businesspack.bd.tables.records;


import java.math.BigDecimal;

import org.example.businesspack.bd.tables.Maintenance;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaintenanceRecord extends UpdatableRecordImpl<MaintenanceRecord> implements Record3<Integer, String, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>maintenance.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>maintenance.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>maintenance.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>maintenance.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>maintenance.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>maintenance.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Maintenance.MAINTENANCE.ID;
    }

    @Override
    public Field<String> field2() {
        return Maintenance.MAINTENANCE.NAME;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Maintenance.MAINTENANCE.AMOUNT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public BigDecimal component3() {
        return getAmount();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public BigDecimal value3() {
        return getAmount();
    }

    @Override
    public MaintenanceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MaintenanceRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public MaintenanceRecord value3(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public MaintenanceRecord values(Integer value1, String value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MaintenanceRecord
     */
    public MaintenanceRecord() {
        super(Maintenance.MAINTENANCE);
    }

    /**
     * Create a detached, initialised MaintenanceRecord
     */
    public MaintenanceRecord(Integer id, String name, BigDecimal amount) {
        super(Maintenance.MAINTENANCE);

        setId(id);
        setName(name);
        setAmount(amount);
        resetChangedOnNotNull();
    }
}
