/*
 * This file is generated by jOOQ.
 */
package org.example.businesspack.bd.tables.records;


import org.example.businesspack.bd.tables.TabStatus;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabStatusRecord extends TableRecordImpl<TabStatusRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tab_status.tab_name</code>.
     */
    public void setTabName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tab_status.tab_name</code>.
     */
    public String getTabName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tab_status.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tab_status.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TabStatus.TAB_STATUS.TAB_NAME;
    }

    @Override
    public Field<String> field2() {
        return TabStatus.TAB_STATUS.STATUS;
    }

    @Override
    public String component1() {
        return getTabName();
    }

    @Override
    public String component2() {
        return getStatus();
    }

    @Override
    public String value1() {
        return getTabName();
    }

    @Override
    public String value2() {
        return getStatus();
    }

    @Override
    public TabStatusRecord value1(String value) {
        setTabName(value);
        return this;
    }

    @Override
    public TabStatusRecord value2(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public TabStatusRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabStatusRecord
     */
    public TabStatusRecord() {
        super(TabStatus.TAB_STATUS);
    }

    /**
     * Create a detached, initialised TabStatusRecord
     */
    public TabStatusRecord(String tabName, String status) {
        super(TabStatus.TAB_STATUS);

        setTabName(tabName);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
