/*
 * This file is generated by jOOQ.
 */
package org.example.businesspack.bd.tables.records;


import org.example.businesspack.bd.tables.UserData;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDataRecord extends UpdatableRecordImpl<UserDataRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_data.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_data.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user_data.telegram_name</code>.
     */
    public void setTelegramName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_data.telegram_name</code>.
     */
    public String getTelegramName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_data.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_data.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserData.USER_DATA.ID;
    }

    @Override
    public Field<String> field2() {
        return UserData.USER_DATA.TELEGRAM_NAME;
    }

    @Override
    public Field<String> field3() {
        return UserData.USER_DATA.EMAIL;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTelegramName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTelegramName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public UserDataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserDataRecord value2(String value) {
        setTelegramName(value);
        return this;
    }

    @Override
    public UserDataRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserDataRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDataRecord
     */
    public UserDataRecord() {
        super(UserData.USER_DATA);
    }

    /**
     * Create a detached, initialised UserDataRecord
     */
    public UserDataRecord(Integer id, String telegramName, String email) {
        super(UserData.USER_DATA);

        setId(id);
        setTelegramName(telegramName);
        setEmail(email);
        resetChangedOnNotNull();
    }
}
