spring:
  application:
    name: notification-app
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:/data/notification-app
    username: test
    password: test
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
server:
  port: 8081