spring:
  config:
    import: optional:file:notification-app\.env[.properties]
  application:
    name: notification-app
  h2:
    console.enabled: true
  datasource:
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.yandex.ru
server:
  port: 8081