spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification-app
  h2:
    console.enabled: true
  datasource:
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.yandex.ru
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus  # Открываем endpoint /actuator/prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8081

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  template: "Доброго времени суток, %s!\nВы не завершили оформление документов: %s"

mail:
  address: "stretensky.danila@yandex.ru"
  template: |
    <b>Доброго времени суток, дорогой пользователь!</b><br>
    <p>Не забудь завершить заполнение следующих документов: %s</p><br><br>
    <small>С уважением,</small><br>
    <small>Команда BusinessPack</small><br>
    <small><i>Связаться с нами: %s</i></small>
