/*
 * This file is generated by jOOQ.
 */
package org.example.businesspack.bd.tables;


import java.util.function.Function;

import org.example.businesspack.bd.DefaultSchema;
import org.example.businesspack.bd.tables.records.TabStatusRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabStatus extends TableImpl<TabStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tab_status</code>
     */
    public static final TabStatus TAB_STATUS = new TabStatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TabStatusRecord> getRecordType() {
        return TabStatusRecord.class;
    }

    /**
     * The column <code>tab_status.tab_name</code>.
     */
    public final TableField<TabStatusRecord, String> TAB_NAME = createField(DSL.name("tab_name"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>tab_status.status</code>.
     */
    public final TableField<TabStatusRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    private TabStatus(Name alias, Table<TabStatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private TabStatus(Name alias, Table<TabStatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>tab_status</code> table reference
     */
    public TabStatus(String alias) {
        this(DSL.name(alias), TAB_STATUS);
    }

    /**
     * Create an aliased <code>tab_status</code> table reference
     */
    public TabStatus(Name alias) {
        this(alias, TAB_STATUS);
    }

    /**
     * Create a <code>tab_status</code> table reference
     */
    public TabStatus() {
        this(DSL.name("tab_status"), null);
    }

    public <O extends Record> TabStatus(Table<O> child, ForeignKey<O, TabStatusRecord> key) {
        super(child, key, TAB_STATUS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public TabStatus as(String alias) {
        return new TabStatus(DSL.name(alias), this);
    }

    @Override
    public TabStatus as(Name alias) {
        return new TabStatus(alias, this);
    }

    @Override
    public TabStatus as(Table<?> alias) {
        return new TabStatus(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TabStatus rename(String name) {
        return new TabStatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabStatus rename(Name name) {
        return new TabStatus(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabStatus rename(Table<?> name) {
        return new TabStatus(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
